package vm

// Code generated by go generate; DO NOT EDIT.
const (
	opAdd        = 1
	opAddp       = 2
	opArg        = 3
	opAux        = 4
	opBelleq     = 5
	opBufread    = 6
	opBufwrite   = 7
	opClip       = 8
	opCompressor = 9
	opCrush      = 10
	opDbgain     = 11
	opDelay      = 12
	opDistort    = 13
	opEnvelope   = 14
	opFilter     = 15
	opGain       = 16
	opHold       = 17
	opIn         = 18
	opInvgain    = 19
	opLoadnote   = 20
	opLoadval    = 21
	opMcdelay    = 22
	opMcfilter   = 23
	opMcloop     = 24
	opMcloopend  = 25
	opMcmix      = 26
	opMcspread   = 27
	opMcsum      = 28
	opMul        = 29
	opMulp       = 30
	opNoise      = 31
	opOscillator = 32
	opOtt        = 33
	opOut        = 34
	opOutaux     = 35
	opPan        = 36
	opPop        = 37
	opPush       = 38
	opReceive    = 39
	opSend       = 40
	opSpawn      = 41
	opSpblur     = 42
	opSpcomb     = 43
	opSpcompress = 44
	opSpcopy     = 45
	opSpcross    = 46
	opSpeed      = 47
	opSpfft      = 48
	opSpfilter   = 49
	opSpformant  = 50
	opSpgate     = 51
	opSpifft     = 52
	opSpphase    = 53
	opSpscale    = 54
	opSync       = 55
	opWindow     = 56
	opXch        = 57
)

var transformCounts = [...]int{0, 0, 0, 1, 3, 4, 1, 0, 5, 1, 1, 4, 1, 6, 2, 1, 1, 0, 1, 0, 1, 2, 1, 1, 0, 0, 1, 2, 0, 0, 2, 6, 7, 1, 2, 1, 0, 0, 0, 1, 3, 2, 2, 2, 0, 2, 0, 0, 3, 2, 1, 1, 1, 2, 0, 2, 0}
