package vm

// Code generated by go generate; DO NOT EDIT.
const (
	opAdd        = 1
	opAddp       = 2
	opArg        = 3
	opAux        = 4
	opBelleq     = 5
	opBufread    = 6
	opBufwrite   = 7
	opClip       = 8
	opCompressor = 9
	opCrush      = 10
	opDbgain     = 11
	opDelay      = 12
	opDistort    = 13
	opEnvelope   = 14
	opFilter     = 15
	opGain       = 16
	opHold       = 17
	opIn         = 18
	opInvgain    = 19
	opLoadnote   = 20
	opLoadval    = 21
	opMul        = 22
	opMulp       = 23
	opNoise      = 24
	opOscillator = 25
	opOut        = 26
	opOutaux     = 27
	opPan        = 28
	opPop        = 29
	opPush       = 30
	opReceive    = 31
	opSend       = 32
	opSpawn      = 33
	opSpblur     = 34
	opSpcomb     = 35
	opSpcompress = 36
	opSpcopy     = 37
	opSpcross    = 38
	opSpeed      = 39
	opSpfft      = 40
	opSpfilter   = 41
	opSpformant  = 42
	opSpgate     = 43
	opSpifft     = 44
	opSpphase    = 45
	opSpscale    = 46
	opSync       = 47
	opWindow     = 48
	opXch        = 49
)

var transformCounts = [...]int{0, 0, 0, 1, 3, 4, 1, 0, 5, 1, 1, 4, 1, 5, 2, 1, 1, 0, 1, 0, 1, 0, 0, 2, 6, 1, 2, 1, 0, 0, 0, 1, 3, 2, 2, 2, 0, 2, 0, 0, 3, 2, 1, 1, 1, 2, 0, 2, 0}
