package vm

// Code generated by go generate; DO NOT EDIT.
const (
	opAdd        = 1
	opAddp       = 2
	opArg        = 3
	opAux        = 4
	opBelleq     = 5
	opBufread    = 6
	opBufwrite   = 7
	opClip       = 8
	opCompressor = 9
	opCrush      = 10
	opDbgain     = 11
	opDelay      = 12
	opDistort    = 13
	opEnvelope   = 14
	opFilter     = 15
	opGain       = 16
	opHold       = 17
	opIn         = 18
	opInvgain    = 19
	opLoadnote   = 20
	opLoadval    = 21
	opMul        = 22
	opMulp       = 23
	opNoise      = 24
	opOscillator = 25
	opOtt        = 26
	opOut        = 27
	opOutaux     = 28
	opPan        = 29
	opPop        = 30
	opPush       = 31
	opReceive    = 32
	opSend       = 33
	opSpawn      = 34
	opSpblur     = 35
	opSpcomb     = 36
	opSpcompress = 37
	opSpcopy     = 38
	opSpcross    = 39
	opSpeed      = 40
	opSpfft      = 41
	opSpfilter   = 42
	opSpformant  = 43
	opSpgate     = 44
	opSpifft     = 45
	opSpphase    = 46
	opSpscale    = 47
	opSync       = 48
	opWindow     = 49
	opXch        = 50
)

var transformCounts = [...]int{0, 0, 0, 1, 3, 4, 1, 0, 5, 1, 1, 4, 1, 6, 2, 1, 1, 0, 1, 0, 1, 0, 0, 2, 6, 7, 1, 2, 1, 0, 0, 0, 1, 3, 2, 2, 2, 0, 2, 0, 0, 3, 2, 1, 1, 1, 2, 0, 2, 0}
