// Generated by sointu-compile -js; do not edit. See FORK.md, "Web runtime".

/** A song that renders in the background and plays while it renders. */
export interface Song {
  /** The audio context the song plays in, at 44100 Hz. Created suspended until a user gesture. */
  readonly context: AudioContext;
  /** Seconds of the song rendered so far; equals `duration` when all is rendered. */
  readonly rendered: number;
  /** Resolves when the song can start: the runway is rendered, and rendering will stay ahead of playing. */
  readonly ready: Promise<void>;
  /**
   * Starts playing what is rendered, and the rest as it is rendered. Call it
   * in a user gesture, as it resumes the audio context. The song plays into
   * `destination`, a node of `context`; by default its output. Later calls
   * do nothing.
   */
  start(destination?: AudioNode): void;
  /**
   * Seconds of the song played, from the clock of the audio context: 0 before
   * the start. It never goes back, and it stops while the song waits for
   * the renderer, should playing catch up with it.
   */
  time(): number;
}

/**
 * Starts rendering the song.
 * @param wasm the bytes of the .wasm player compiled from the song
{{- if .SeparateSamples}}
 * @param sampleFiles the bytes of the {{.Samples}} sample file{{if gt .Samples 1}}s written next to it, in the order of their numbers{{else}} written next to it{{end}}
{{- end}}
 * @param runway seconds to render before the song is ready, 2 by default
 */
export function load(wasm: BufferSource{{if .SeparateSamples}}, sampleFiles: BufferSource[]{{end}}, runway?: number): Song;

/** Length of the song in seconds. */
export const duration: number;
/** Rows of the song played in a second: `row = song.time() * rowsPerSecond`. */
export const rowsPerSecond: number;
/** Rows of a pattern. */
export const rowsPerPattern: number;
