// Generated by sointu-compile -js{{if .Stages}} -stages {{.Stages}}{{end}}{{if .SeparateSamples}} -samples{{end}}{{if .RowSync}} -r{{end}}{{if .OutputClock}} -outputclock{{end}}; do not edit. See FORK.md, "Web runtime".
//
// Renders the song in the background and plays it while it renders:
//
//   import { load } from "./song.js";
//   const song = load(wasmBytes);       // starts rendering
//   await song.ready;                   // enough is rendered to play without catching up
//   button.onclick = () => song.start(); // needs a user gesture
//   song.time();                        // seconds of the song played, for the visuals
{{- if .OutputClock}}
//
// The clock is that of the output: where the context says the output is
// (getOutputTimestamp: a time of the context and the time of the page it was
// at the output), carried on with the time of the page, so it is behind the
// time of the context by the output latency and moves between audio blocks.
// Firefox takes the timestamp when asked, both times the latency ago: carried
// on, that is the time of the context again, so there the clock is the time
// of the timestamp alone, behind by the latency, a block at a time.
{{- end}}

/** Length of the song in seconds. */
export const duration = {{.Frames}} / 44100;
/** Rows of the song played in a second: row = song.time() * rowsPerSecond. */
export const rowsPerSecond = 44100 / {{.RowSamples}};
/** Rows of a pattern. */
export const rowsPerPattern = {{.Song.Score.RowsPerPattern}};
{{- if .SyncValues}}
/** Number of sync values: {{if .RowSync}}the row, then {{end}}the signals at the sync units, in the order of the patch. */
export const syncChannels = {{.SyncValues}};
{{- end}}

// The renderer instantiates the player and renders the song. It runs in a
// worker made from its source text, and on the main thread when there are no
// workers, a row at a time with the page running in between (slow): it must
// use nothing outside itself. post gets the audio in pieces of half a
// second, as interleaved stereo samples: a piece that starts on a quarter of
// a second has a start time that the browser turns into exactly its frame;
// from any other time it may get a fraction of a frame, and interpolate.
{{- if .Stages}}
// With a stage, the instance renders the voices of that stage of the pipeline:
// for each chunk of rows, it reads the tape from source, unless it is the
// first stage, and sends its own tape to sink, unless it is the last, which
// posts the audio.
{{- end}}
{{- if .SyncValues}}
// The sync values, {{.SyncValues}} for every 256th sample, are posted with the audio:
// those of the samples of the piece.{{if .Stages}} A stage gets those of the stages
// before it with the tape, and adds its own.{{end}}
{{- end}}
const renderer = (post, slow) => (module{{if .Stages}}, stage, source, sink{{end}}{{if .Samples}}, samples{{end}}) =>
  WebAssembly.instantiate(module, { {{- if .MathImports}} m: Math{{if .Samples}},{{end}}{{end}}{{if .Samples}} s: { b: (i, f, c) => samples[i][c][f] || 0 }{{end}} }).then(({ exports: { m, r{{if .Stages}}, g{{end}} } }) => {
    let row = 0,
      sent = 0; // frames posted
{{- if .SyncValues}}
    // the number of sync values before a frame
    const synced = (frame) => Math.ceil(frame / 256) * {{.SyncValues}};
{{- end}}
    const step = ({{if .Stages}}tape{{end}}) => {
{{- if .Stages}}
      const rows = slow ? 1 : Math.min({{.ChunkRows}}, {{.Rows}} - row);
{{- if .SyncValues}}
      const from = synced(row * {{.RowSamples}});
      if (tape) {
        new Uint8Array(m.buffer, {{.TapeIn}}).set(tape.data[0]);
        new Float32Array(m.buffer, {{.Sync}} + from * 4).set(tape.data[1]);
      }
{{- else}}
      tape && new Uint8Array(m.buffer, {{.TapeIn}}).set(tape.data);
{{- end}}
      r(rows);
      row += rows;
      if (sink) {
        const out = new Uint8Array(m.buffer, {{.TapeOut}}, rows * {{.RowSamples}} * [{{range $i, $c := .StageCells}}{{if $i}}, {{end}}{{$c}}{{end}}][stage + 1] * 4).slice();
{{- if .SyncValues}}
        const sync = new Float32Array(m.buffer, {{.Sync}} + from * 4, synced(row * {{.RowSamples}}) - from).slice();
        sink.postMessage([out, sync], [out.buffer, sync.buffer]);
{{- else}}
        sink.postMessage(out, [out.buffer]);
{{- end}}
      }
{{- else}}
      r(1);
      row++;
{{- end}}
      // every whole piece rendered, and at the end of the song the rest
      for (let n; {{if .Stages}}!sink && {{end}}(n = Math.min(22050, row * {{.RowSamples}} - sent)) > (row < {{.Rows}} ? 22049 : 0); sent += n) {
        const audio = new {{if .Output16Bit}}Int16Array{{else}}Float32Array{{end}}(m.buffer, {{.Output}} + sent * {{.FrameBytes}}, n * 2).slice();
{{- if .SyncValues}}
        const sync = new Float32Array(m.buffer, {{.Sync}} + synced(sent) * 4, synced(sent + n) - synced(sent)).slice();
        post([audio, sync], [audio.buffer, sync.buffer]);
{{- else}}
        post(audio, [audio.buffer]);
{{- end}}
      }
      slow && row < {{.Rows}} && setTimeout(step);
    };
{{- if .Stages}}
    if (stage + 1) g(stage);
    if (source) source.onmessage = step;
    else
{{- end}}
    do step();
    while (!slow && row < {{.Rows}});
  });

/**
 * Starts rendering the song from the bytes of the .wasm
{{- if .SeparateSamples}} and the bytes of its
 * {{.Samples}} sample file{{if gt .Samples 1}}s, in order{{end}}
{{- end}}. The song is ready when
 * runway seconds are rendered and rendering the rest, at margin times the
 * speed measured so far, will stay ahead of playing.
 */
export const load = (wasm{{if .SeparateSamples}}, sampleFiles{{end}}, runway = 2, margin = 0.8) => {
  const context = new AudioContext({ sampleRate: 44100 });
{{- if .SyncValues}}
  const syncs = new Float32Array({{mul .SyncValues .SyncTicks}});
  let synced = 0; // sync values received
{{- end}}
  let end = 0, // frames rendered
    top = 0, // the latest time reported
    waiting = [], // pieces rendered before the start
    t0, // context time where the song starts, a multiple of a quarter of a second
    began,
    ready,
    output;
  const schedule = (buffer, at) => {
    const source = context.createBufferSource();
    source.buffer = buffer;
    source.connect(output);
    // a piece that comes after its time makes the song wait for it
    if (t0 + at < context.currentTime) t0 = Math.ceil(context.currentTime * 4 + 0.2) / 4 - at;
    source.start(t0 + at);
  };
  const add = ({{if .SyncValues}}[audio, sync]{{else}}audio{{end}}) => {
{{- if .SyncValues}}
    syncs.set(sync, synced);
    synced += sync.length;
{{- end}}
    const n = audio.length / 2,
      buffer = context.createBuffer(2, n, 44100),
      left = buffer.getChannelData(0),
      right = buffer.getChannelData(1);
    for (let i = 0; i < n; i++) {
      left[i] = audio[2 * i]{{if .Output16Bit}} / 32767{{end}};
      right[i] = audio[2 * i + 1]{{if .Output16Bit}} / 32767{{end}};
    }
    output ? schedule(buffer, song.rendered) : waiting.push([buffer, song.rendered]);
    song.rendered = (end += n) / 44100;
    // ready with the runway, and when rendering the rest at margin times the
    // speed so far ends before the song gets there
    if (song.rendered >= Math.min(duration, Math.max(runway, duration * (1 - (margin * 1000 * song.rendered) / (performance.now() - began))))) ready();
  };
  const song = {
    context,
    rendered: 0,
    ready: new Promise((resolve) => (ready = resolve)),
    start(destination = context.destination) {
      if (!output) {
        context.resume();
        output = destination;
        // on the next quarter of a second that is 50 ms away or more
        t0 = Math.ceil(context.currentTime * 4 + 0.2) / 4;
        waiting.map((piece) => schedule(...piece));
      }
    },
{{- if .OutputClock}}
    time() {
      // where the output is: the time of the timestamp, carried on, unless
      // that reaches the time of the context (less a millisecond), as in
      // Firefox, or when the context stands still. Without a timestamp (no
      // such method, or zeros, as before the context runs), the time of the
      // context
      const now = context.currentTime,
        { contextTime, performanceTime } = context.getOutputTimestamp?.() || 0,
        output = contextTime + (performance.now() - performanceTime) / 1000;
      return (top = Math.max(top, Math.min((performanceTime ? (output < now - 1e-3 ? output : contextTime) : now) - t0, song.rendered)) || 0);
    },
{{- else}}
    time: () => (top = Math.max(top, Math.min(context.currentTime - t0, song.rendered)) || 0),
{{- end}}
{{- if .SyncValues}}
    sync: (channel, time = song.time()) => syncs[Math.min({{sub .SyncTicks 1}}, Math.floor((time * 44100) / 256)) * {{.SyncValues}} + channel],
{{- end}}
  };
  WebAssembly.compile(wasm).then({{if .Samples}}async {{end}}(module) => {
{{- if .Samples}}
    // the samples are decoded here: workers cannot
    const samples = (
      await Promise.all(
        {{if .SeparateSamples}}sampleFiles{{else}}WebAssembly.Module.customSections(module, "sointu.buffer"){{end}}.map((s) => context.decodeAudioData(new Uint8Array(s).slice().buffer)),
      )
    ).map((b) => [b.getChannelData(0), b.getChannelData(b.numberOfChannels - 1)]);
{{- end}}
    began = performance.now();
    try {
      const url = URL.createObjectURL(new Blob([`onmessage=e=>(${renderer})(postMessage)(...e.data)`]));
{{- if .Stages}}
      for (let stage = 0, source; stage < {{.Stages}}; stage++) {
        const worker = new Worker(url),
          channel = stage < {{.Stages}} - 1 && new MessageChannel();
        worker.onmessage = (e) => add(e.data);
        worker.postMessage([module, stage, source, channel.port1{{if .Samples}}, samples{{end}}], [source, channel.port1].filter((p) => p));
        source = channel.port2;
      }
{{- else}}
      const worker = new Worker(url);
      worker.onmessage = (e) => add(e.data);
      worker.postMessage([module{{if .Samples}}, samples{{end}}]);
{{- end}}
    } catch {
      // no workers: on the main thread
      renderer(add, 1)(module{{if .Stages}}, -1, 0, 0{{end}}{{if .Samples}}, samples{{end}});
    }
  });
  return song;
};
